DELETE FROM public.knowledge_topics
WHERE title = 'FUN Profile - Cảnh báo giả mạo Angel Quang Vũ & an toàn ví MetaMask';

INSERT INTO public.knowledge_topics (
  title,
  description,
  content,
  icon,
  category
) VALUES (
  'FUN Profile - Cảnh báo giả mạo Angel Quang Vũ & an toàn ví MetaMask',
  'Cảnh báo an toàn FUN.RICH: tài khoản giả mạo, scam, lừa đảo, MetaMask, seed phrase, private key, mật khẩu ví, Developer Tools, F12, KeyringController, ký dữ liệu lạ, Angel Quang Vũ, angeiquangvu, angelquangvu.',
  E'## Cảnh báo khẩn cấp về tài khoản giả mạo và an toàn ví\n\nFUN.RICH đã ghi nhận một tài khoản có dấu hiệu giả mạo danh tính Angel Quang Vũ bằng cách thay đổi rất nhỏ username để gây nhầm lẫn.\n\n- Tài khoản chính chủ của Angel Quang Vũ: https://fun.rich/angelquangvu\n- Tài khoản nghi giả mạo cần cảnh giác: https://fun.rich/angeiquangvu\n\nTài khoản nghi giả mạo được báo cáo là có đăng video hướng dẫn người xem thao tác với dữ liệu nội bộ của ví MetaMask và yêu cầu công khai hoặc ký dữ liệu mà người dùng có thể không hiểu rõ. Đây không phải quy trình xác thực chính thức của MetaMask, BNB Smart Chain hay FUN.RICH.\n\n## Angel AI phải trả lời thế nào khi người dùng hỏi\n\nNếu người dùng hỏi về `angeiquangvu`, video yêu cầu mở Developer Tools/F12, KeyringController, seed phrase, private key, mật khẩu ví, ký dữ liệu lạ, hoặc quy trình xác thực ví đáng ngờ, Angel AI phải ưu tiên cảnh báo an toàn:\n\n1. Không làm theo hướng dẫn trong video hoặc bài đăng đáng ngờ.\n2. Không mở Developer Tools/F12 để tìm, sao chép, dán hoặc công khai dữ liệu nội bộ của ví theo yêu cầu của người khác.\n3. Không chia sẻ Seed Phrase, Private Key, mật khẩu ví, dữ liệu KeyringController hoặc bất kỳ dữ liệu bảo mật nào của ví.\n4. Không ký giao dịch, ký tin nhắn hoặc công khai dữ liệu nếu chưa hiểu rõ mục đích và bên yêu cầu chưa được xác minh.\n5. Kiểm tra thật kỹ username, link hồ sơ và dấu xác thực trước khi tin bất kỳ hướng dẫn nào liên quan đến ví, tài sản số hoặc bảo mật tài khoản.\n6. Chỉ theo dõi thông tin từ tài khoản chính chủ đã được xác thực và kênh chính thức của FUN.RICH.\n7. Báo cáo ngay cho FUN.RICH, Coordinator hoặc đội ngũ hỗ trợ nếu phát hiện tài khoản giả mạo, nội dung lừa đảo, scam ví hoặc hướng dẫn yêu cầu tiết lộ dữ liệu bảo mật.\n\n## Nội dung cần nhấn mạnh\n\n- `https://fun.rich/angelquangvu` là tài khoản chính chủ được nêu trong cảnh báo.\n- `https://fun.rich/angeiquangvu` là tài khoản nghi giả mạo được nêu trong cảnh báo.\n- Việc thêm hoặc đổi một ký tự trong username là dấu hiệu giả mạo phổ biến nhằm đánh lừa người dùng.\n- MetaMask, BNB Smart Chain và FUN.RICH không yêu cầu người dùng tiết lộ Seed Phrase, Private Key, mật khẩu ví hoặc dữ liệu nội bộ ví để xác thực.\n- Khi nghi ngờ, hành động an toàn nhất là dừng lại, không ký gì, không gửi dữ liệu gì, chụp lại bằng chứng nếu cần và báo cáo cho đội ngũ FUN.RICH.\n\n## Lưu ý an toàn cho Angel AI\n\nAngel AI không được hướng dẫn từng bước cách truy cập dữ liệu nội bộ MetaMask, không hướng dẫn cách trích xuất KeyringController, không yêu cầu người dùng paste dữ liệu ví vào chat, và không xác nhận quy trình đáng ngờ là an toàn. Nếu người dùng đã lỡ làm theo, Angel AI nên khuyên họ ngắt kết nối ví khỏi website lạ, không ký thêm, chuyển tài sản sang ví mới an toàn nếu nghi private key/seed phrase bị lộ, và liên hệ hỗ trợ chính thức.',
  '🛡️',
  'FUN Ecosystem'
);
